default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 12345678
  host: db

development:
  <<: *default
  database: blu_project_development

test:
  <<: *default
  database: blu_project_test

production:
  <<: *default
  database: blu_project_production
  username: postgres
  password: 12345678